'use strict';
const E=window.Elderfall,$=s=>document.querySelector(s),SAVE='elderfall-campaign-v3';
const portraits=['knight','mage','ranger','priest'],slotNames={weapon:'무기',armor:'갑옷',trinket:'장신구'},colorNames=['공격','마법','방어'],stanceNames={assault:'강습 · 공격 +1',focus:'집중 · 마법 +2 / 에너지 1',guard:'방어 · 방어 +2',recover:'회복 · 파티 치유 / 에너지 1'};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state=null,storageAvailable=true,folio=null,inspected=null,pinned=null,resultDismissed=false;
let battleHero=0,chosenSkill=null,skillTarget=null,rerollMode=false,busy=false,fastMotion=false,demoMode=false,campaignBeforeDemo=null,lootQuest=null,lootChoice=null;
E.classes.forEach((c,i)=>{const label=document.createElement('label');label.className='class-choice';label.innerHTML=`<span class="portrait portrait-${portraits[i]}" aria-hidden="true"></span><input type="checkbox" value="${i}" ${i===0?'checked':''}><strong>${c.name}</strong><small>${c.role}</small>`;$('#class-picker').append(label);});
function message(text){$('#feedback').textContent=text;clearTimeout(message.timer);message.timer=setTimeout(()=>$('#feedback').textContent='',4200);}
function persist(){if(demoMode)return;try{localStorage.setItem(SAVE,JSON.stringify(state));}catch{storageAvailable=false;}}
function button(text,type,arg={},disabled=false,extra=''){return `<button data-action="${type}" data-arg="${esc(JSON.stringify(arg))}" ${disabled?'disabled':''} ${extra}>${text}</button>`;}
const pause=ms=>new Promise(resolve=>setTimeout(resolve,fastMotion||matchMedia('(prefers-reduced-motion: reduce)').matches?0:ms));
async function act(type,arg={}){
 if(busy)return false;
 try{
  const animating=['roll','reroll','resolve'].includes(type),snapshot=type==='resolve'?{preview:E.tacticalPreview(state),enemy:state.enemies.find(e=>e.id===state.battle.enemy),participants:[...state.battle.participants]}:null;
  E.apply(state,type,arg);if(demoMode&&type==='roll'&&state.battle.round===1){const counters=[0,0,0],values=[[5,2,4],[3,1,5],[4,1,2]];state.battle.dice.forEach(d=>{d.value=values[d.color][counters[d.color]++%3];});}inspected=null;persist();
  if(animating){busy=true;document.body.classList.add('animating');}
  if(type==='engage'){battleHero=state.battle.participants[0];chosenSkill=null;rerollMode=false;}
  if(type==='resolve'){
   $('#battle-cue').textContent='기술 발동';$('#combat-scene').classList.add('attack-flash');await pause(380);
   $('#battle-cue').textContent=`적에게 피해 ${snapshot.preview.damage}`;$('#battle-enemy-card').classList.add('taking-hit');await pause(450);
   if(snapshot.enemy.hp>0){$('#battle-cue').textContent='적 반격 · 영웅 체력 변화';$('#battle-hero-card').classList.add('taking-hit');await pause(450);}
   $('#combat-scene').classList.remove('attack-flash');$('#battle-enemy-card').classList.remove('taking-hit');$('#battle-hero-card').classList.remove('taking-hit');chosenSkill=null;rerollMode=false;
  }
  render();
  if(type==='roll'||type==='reroll'){
   const dice=type==='roll'?[...document.querySelectorAll('.die')]:[document.querySelector(`.die[data-die="${arg.index}"]`)];dice.filter(Boolean).forEach(el=>el.classList.add('rolling'));$('#battle-cue').textContent='주사위를 굴립니다…';await pause(780);dice.filter(Boolean).forEach(el=>el.classList.remove('rolling'));$('#battle-cue').textContent='';
  }
  if(animating){busy=false;document.body.classList.remove('animating');render();}
  if(['claim','talent','equip','buy','explore'].includes(type))message(state.log[0]);
  if(type==='resolve'&&state.lastResult){message(state.lastResult.title+' · '+state.lastResult.text);if(!state.battle&&!state.outcome&&state.lastResult.title==='전투 승리')openVictory();}
  return true;
 }catch(e){busy=false;document.body.classList.remove('animating');message(e.message);return false;}
}
function locationName(pos){return E.locations[pos]?.name||'황야 '+pos;}
function currentGoal(){const h=E.hero(state);return h.quests.find(q=>q.id===pinned)||h.quests.find(q=>q.ready)||h.quests[0];}
function hint(){const h=E.hero(state),q=currentGoal(),def=q&&E.quests.find(x=>x.id===q.id);if(state.outcome)return state.outcome==='win'?'잿빛 왕국에 평화가 찾아왔습니다. 영웅의 성장 기록을 살펴보세요.':'모험 종료 · 새 캠페인에서 다른 경로와 빌드를 시도해 보세요.';if(state.battle)return state.battle.phase==='plan'?'적의 다음 공격을 확인하세요. 준비 태세를 고른 뒤 주사위를 함께 굴립니다.':'기술 선택 → 주사위 터치로 배치. 재굴림은 별도 버튼에서 선택합니다. 배치한 주사위는 기본 공격에서 빠집니다.';if(!state.actions)return '행동을 모두 사용했습니다. 「차례 마치기」로 다음 영웅에게 넘기세요.';if(h.points)return `레벨 ${E.level(h)} 달성! 「영웅」에서 특성을 선택하면 전투 주사위와 능력이 강화됩니다.`;if(q?.ready)return `${def.name} 목표 달성 · 가까운 거점으로 돌아가 「퀘스트」에서 장비 보상을 골라 보고하세요.`;if(q)return `${def.name} → ${locationName(def.pos)} ${def.pos} · ${def.type==='hunt'?'전투 승리':def.type==='escort'?'상단 호위':'지역 조사'} 후 거점에 보고.`;if(state.seals>=2&&E.level(h)>=3)return '레이드 준비 완료 · D1 잿빛 용의 둥지로 이동하세요. 세 번째 봉인을 모으면 용 체력이 6 감소합니다.';return '거점에서 새 퀘스트를 수락하세요. 봉인 2개와 레벨 3이 되면 잿빛 용에 도전할 수 있습니다.';}
function render(){
 $('#setup').hidden=!!state;$('#game').hidden=!state;document.querySelectorAll('.play-menu').forEach(b=>b.hidden=!state);document.body.classList.toggle('in-battle',!!state?.battle);if(!state)return;
 const h=E.hero(state),c=E.classes[h.classId],st=E.stats(h),can=!state.outcome&&!state.battle&&state.actions>0&&h.hp>0;
 $('#turn-title').textContent=`${c.name} · Lv.${E.level(h)}`;$('#round-label').textContent=`라운드 ${state.round} / 20`;$('#round-track').innerHTML=Array.from({length:20},(_,i)=>`<i class="${i+1===state.round?'now':i+1<state.round?'past':''}"></i>`).join('');$('#seal-track').innerHTML=Array.from({length:3},(_,i)=>i<state.seals?'<b>◆</b>':'◆').join('');$('#save-notice').textContent=demoMode?'연습 · 기록 유지':storageAvailable?'✓ 저장됨':'저장 불가';$('#next-goal').textContent=hint();
 $('#active-portrait').className=`portrait portrait-${portraits[h.classId]}`;$('#hero-name').textContent=c.name;$('#hero-summary').textContent=`${h.pos} · 체력 ${h.hp}/${st.hp} · 경험치 ${h.xp}`;$('#resources').innerHTML=[['에너지',h.energy+'/4'],['골드',h.gold],['보급',h.supply],['물약',h.potions]].map(([name,value])=>`<span>${name}<b>${value}</b></span>`).join('');
 renderMap(can);
 renderLocation();$('#event-name').textContent=state.event===null?'모험의 첫날':E.events[state.event].name;$('#event-text').textContent=state.event===null?'3라운드마다 세계 사건 발생 · 거점과 보급을 활용하세요.':E.events[state.event].desc;
 $('#party').style.setProperty('--party-size',state.heroes.length);$('#party').innerHTML=state.heroes.map((x,i)=>{const cs=E.classes[x.classId],xs=E.stats(x);return `<button class="party-card ${i===state.active?'active':''}" data-inspect="${i}" aria-label="${cs.name} 영웅 카드"><span class="portrait portrait-${portraits[x.classId]}" aria-hidden="true"></span><div><h3>${cs.name} · Lv.${E.level(x)} ${x.points?'<span class="new-point">특성 +'+x.points+'</span>':''}</h3><p>${x.pos} · HP ${x.hp}/${xs.hp} · 에너지 ${x.energy}</p><meter min="0" max="${xs.hp}" value="${x.hp}" aria-label="${cs.name} 체력"></meter><p>공격 ${xs.red} · 마법 ${xs.blue} · 방어 ${xs.green}</p></div></button>`;}).join('');
 $('#action-budget').innerHTML=`<span>${state.battle?'교전':'행동'}</span><div>${Array.from({length:state.heroes.length===1?4:3},(_,i)=>`<i class="${i<state.actions?'on':''}"></i>`).join('')}</div>`;
 $('#world-scene').hidden=!!state.battle;$('#combat-scene').hidden=!state.battle;$('#world-actions').hidden=!!state.battle;$('#battle-actions').hidden=!state.battle;
 const gather=h.quests.find(q=>!q.ready&&E.quests.find(x=>x.id===q.id)?.pos===h.pos&&E.quests.find(x=>x.id===q.id)?.type==='gather');$('#explore').disabled=!can||!gather||gather.id==='relic'&&h.energy<2||gather.id==='stars'&&h.supply<1;$('#engage').disabled=!can||!E.canEngage(state);$('#rest').disabled=!can||!E.town(h.pos)&&h.supply<1||h.hp===st.hp&&h.energy===4;$('#end-turn').disabled=!!state.outcome||!!state.battle;
 updateTravelSelection();
 $('#rest small').textContent=E.town(h.pos)?'여관 +6 HP · +2 에너지':'야영 +3 HP · 보급 1';
 if(state.battle)renderBattle();if(folio&&$('#sheet').open)renderFolio();
 if(state.outcome&&!resultDismissed&&!$('#result').open){$('#sheet').close();folio=null;$('#result-title').textContent=state.outcome==='win'?'잿빛 용을 물리쳤습니다':'왕국의 마지막 날';$('#result-text').textContent=`${state.round}라운드 · 봉인 ${state.seals}개 · 완료 퀘스트 ${state.heroes.reduce((n,x)=>n+x.completed.length,0)}개 · ${state.heroes.map(x=>E.classes[x.classId].name+' Lv.'+E.level(x)).join(' / ')}`;$('#result').showModal();}
}
function routeText(trip){return `행동 ${trip.cost}${trip.supply?' · 보급 −'+trip.supply:''}${trip.damage?' · 체력 −'+trip.damage:''}`;}
function renderMap(can){
 const h=E.hero(state),goal=currentGoal(),goalDef=goal&&E.quests.find(q=>q.id===goal.id),svgNS='http://www.w3.org/2000/svg';
 $('#board').replaceChildren();const svg=document.createElementNS(svgNS,'svg');svg.setAttribute('viewBox','0 0 1000 1000');svg.setAttribute('preserveAspectRatio','none');svg.setAttribute('aria-hidden','true');svg.classList.add('map-routes');
 // Fine region borders and visible roads are drawn beneath the physical markers.
 const border=document.createElementNS(svgNS,'path');border.setAttribute('d','M240 0 Q290 210 245 410 T280 700 L245 1000 M420 0 Q460 230 420 450 T430 730 L420 1000 M605 0 Q640 210 610 450 T620 720 L600 1000 M800 0 Q755 200 790 420 T795 680 L800 1000 M0 210 Q250 180 460 210 T1000 205 M0 405 Q270 445 500 400 T1000 415 M0 610 Q250 590 510 620 T1000 615 M0 785 Q250 800 510 795 T1000 780');border.setAttribute('class','region-borders');svg.append(border);
 for(const edge of E.routes){const a=E.locations[edge.a],b=E.locations[edge.b],next=edge.a===h.pos?edge.b:edge.b===h.pos?edge.a:null,trip=next&&E.travelInfo(state,next),guard=state.enemies.find(e=>e.id===edge.guard);const path=document.createElementNS(svgNS,'path');path.setAttribute('d',`M${a.x*10} ${a.y*10} Q${(a.x+b.x)*5+(edge.kind==='ford'?22:0)} ${(a.y+b.y)*5} ${b.x*10} ${b.y*10}`);path.setAttribute('class',`route route-${edge.kind} ${guard?.hp>0?'guarded':''} ${trip?.ok&&can?'route-reachable':''} ${next&&next===inspected?'route-selected':''}`);svg.append(path);
  if(edge.kind==='ford'||edge.kind==='mountain'){const mark=document.createElementNS(svgNS,'text');mark.setAttribute('x',(a.x+b.x)*5);mark.setAttribute('y',(a.y+b.y)*5-10);mark.setAttribute('class','route-symbol');mark.textContent=edge.kind==='ford'?'≈':'▲';svg.append(mark);}
 }
 $('#board').append(svg);
 for(const [pos,loc] of Object.entries(E.locations)){
  const e=state.enemies.find(e=>e.pos===pos&&e.hp>0),trip=E.travelInfo(state,pos),reachable=can&&trip.ok,tile=document.createElement('button');tile.className=`region-node ${pos===h.pos?'current':''} ${reachable?'reachable':''} ${pos===inspected?'inspecting':''} ${loc.kind==='town'?'town-node':''} ${e?'enemy-node':''}`;tile.style.left=loc.x+'%';tile.style.top=loc.y+'%';
  tile.setAttribute('aria-label',`${pos} ${loc.name}${e?' '+e.name+' 체력 '+e.hp:''}${reachable?' 이동 가능 '+routeText(trip):' 지역 정보'}`);tile.dataset.region=pos;
  tile.innerHTML=`${goalDef?.pos===pos&&!goal.ready?'<span class="quest-marker">!</span>':''}<span class="region-medallion ${e?'enemy-portrait enemy-'+e.art:''}">${e?'':loc.kind==='town'?'⌂':loc.kind==='bridge'?'═':loc.kind==='mountain'?'▲':loc.kind==='gather'?'✦':'◆'}</span><span class="region-name">${loc.short}</span><span class="region-tier">${pos} · ${loc.kind==='town'?'거점':'Lv.'+loc.tier}</span><span class="tokens">${state.heroes.filter(x=>x.pos===pos).map(x=>`<span class="token portrait portrait-${portraits[x.classId]} ${x.hp===0?'fallen':''}"></span>`).join('')}</span>`;
  tile.addEventListener('click',()=>{inspected=pos;renderMap(can);renderLocation();updateTravelSelection();if(trip.edge&&!trip.ok)message(trip.reason);if(pos!==h.pos&&!trip.edge)openFolio('travel');});$('#board').append(tile);
 }
}
function updateTravelSelection(){
 const h=E.hero(state),gather=h.quests.find(q=>!q.ready&&E.quests.find(x=>x.id===q.id)?.pos===h.pos&&E.quests.find(x=>x.id===q.id)?.type==='gather'),selected=inspected&&inspected!==h.pos?E.travelInfo(state,inspected):null;
 if(selected?.edge){$('#explore').dataset.travelTo=inspected;$('#explore').innerHTML=`<b>이동 확정 →</b><small>${routeText(selected)}</small>`;$('#explore').disabled=!selected.ok;$('#next-goal').textContent=`${locationName(h.pos)} → ${locationName(inspected)} · ${selected.edge.name} · ${routeText(selected)}${selected.reason?' · '+selected.reason:' · 왼쪽 아래 「이동 확정」을 누르세요.'}`;}
 else{$('#next-goal').textContent=hint();delete $('#explore').dataset.travelTo;$('#explore').innerHTML='<b>지역 조사</b><small>수집 · 탐사 / 행동 1</small>';$('#explore').disabled=!!state.outcome||!!state.battle||state.actions<1||h.hp<=0||!gather||gather.id==='relic'&&h.energy<2||gather.id==='stars'&&h.supply<1;}
}
function renderLocation(){const h=E.hero(state),pos=inspected||h.pos,loc=E.locations[pos],e=state.enemies.find(e=>e.pos===pos&&e.hp>0),trip=E.travelInfo(state,pos);$('#location-card').innerHTML=`<p class="eyebrow">${pos===h.pos?'CURRENT REGION':'REGION PREVIEW'} · ${pos}</p><h3>${loc.name}</h3><p>${pos===h.pos?loc.desc:trip.edge?trip.edge.name+' · '+routeText(trip)+(trip.ok?'':' · '+trip.reason):'직접 연결되지 않은 지역 · 여행 계획에서 경로를 비교하세요.'}</p>${e?`<div class="region-stats"><span>지역 난이도<b>Lv.${loc.tier}</b></span><span>적 체력<b>${e.hp}</b></span></div>`:''}${pos!==h.pos&&trip.edge?button('이동 · '+routeText(trip),'move',{pos},!trip.ok,'class="gold-button"'):pos===h.pos&&e?button('전투 시작','engage',{},state.actions<1||!E.canEngage(state),'class="gold-button"'):'<button data-sheet="travel">여행 경로 · 거점 찾기</button>'}`;}
function travelFolio(){
 const h=E.hero(state),selected=inspected&&inspected!==h.pos?inspected:null,goal=currentGoal(),goalDef=goal&&E.quests.find(q=>q.id===goal.id);
 const destinations=[...new Set([selected,goalDef&&!goal.ready?goalDef.pos:null,'C5','A4','E5'].filter(pos=>pos&&pos!==h.pos))];
 const connections=E.routes.filter(r=>r.a===h.pos||r.b===h.pos).sort((a,b)=>Number(b.a===selected||b.b===selected)-Number(a.a===selected||a.b===selected)).map(edge=>{const pos=edge.a===h.pos?edge.b:edge.a,trip=E.travelInfo(state,pos),loc=E.locations[pos];return `<article class="travel-card ${pos===selected?'selected':''}"><div><p class="eyebrow">${edge.name} · ${loc.kind==='town'?'회복 거점':'지역 Lv.'+loc.tier}</p><h3>${loc.name}</h3><p class="trip-cost">${routeText(trip)}</p>${trip.damage?`<p class="travel-warning">이동 후 체력 ${h.hp-trip.damage}/${E.stats(h).hp}${trip.frontier?' · 낮은 레벨로 진입하면 추가 위험':''}</p>`:''}${trip.reason?`<p class="travel-warning">${trip.reason}</p>`:''}</div>${button('이동 확정 →','move',{pos},!trip.ok,'data-travel="true"')}</article>`;}).join('');
 return `<p class="sheet-note">현재 ${E.locations[h.pos].name} · 남은 행동 ${state.actions} · HP ${h.hp}/${E.stats(h).hp} · 보급 ${h.supply}<br>선으로 연결된 지역만 이동합니다. 비용을 확인한 후 이동을 확정하세요. 위험 피해는 갑옷으로 막을 수 없습니다.</p><div class="folio-tabs"><button data-tab="active" class="${folio.tab==='active'?'active':''}">연결된 길</button><button data-tab="plan" class="${folio.tab==='plan'?'active':''}">목표 · 거점 경로 비교</button></div>${folio.tab==='active'?connections:`<p class="sheet-note">현재 체력·보급·레벨과 열린 통로로 끝까지 갈 수 있는 경로를 비교합니다. 합계는 여러 차례에 나누어 쓰는 여행 비용이며, 중간 휴식이나 구매는 포함하지 않습니다.</p>${destinations.map(pos=>{const plans=E.paths(state,pos);return `<section class="route-plan"><h3>${E.locations[pos].name} · ${pos}</h3>${plans.length?plans.map(plan=>`<article class="travel-card"><div><span class="badge">${plan.label}</span><p>${plan.nodes.map(node=>E.locations[node].short).join(' → ')}</p><p class="trip-cost">합계 행동 ${plan.cost} · 보급 ${plan.supply} · 체력 피해 ${plan.damage}</p></div>${button('첫 구간 이동 →','move',{pos:plan.nodes[1]},!E.travelInfo(state,plan.nodes[1]).ok,'data-travel="true"')}</article>`).join(''):'<p class="travel-warning">현재 조건으로 완주할 경로가 없습니다. 보급·체력을 채우거나 레벨을 올리고, 막힌 지역 적을 처치하세요.</p>'}</section>`;}).join('')}`}`;
}
function dieMarkup(d,index,slot=false){
 const faces={1:[5],2:[1,9],3:[1,5,9],4:[1,3,7,9],5:[1,3,5,7,9],6:[1,3,4,6,7,9]},a=state.battle?.assignments?.find(a=>a.index===index),eligible=chosenSkill&&!E.skillReason(state,battleHero,chosenSkill,index,skillTarget??battleHero);
 const used=state.battle.dice.filter(y=>y.hero===d.hero&&y.rerolled).length,reserved=(state.battle.assignments||[]).filter(y=>y.owner===d.hero).reduce((n,y)=>n+E.technique(state,y.owner,y.id).energy,0),disabled=busy||rerollMode&&(!!a||d.rerolled||state.heroes[d.hero].energy-reserved<1||used>=E.stats(state.heroes[d.hero]).rerolls);
 const content=`<span class="cube" data-value="${d.value}">${Object.entries(faces).map(([value,pips])=>`<span class="cube-face face-${value}">${pips.map(pos=>`<i style="grid-area:${Math.ceil(pos/3)} / ${(pos-1)%3+1}"></i>`).join('')}</span>`).join('')}</span>`;
 if(slot)return `<span class="slot-die ${['red','blue','green'][d.color]}">${content}</span>`;
 return `<button class="die ${['red','blue','green'][d.color]} ${a?'assigned':''} ${eligible?'eligible':''} ${d.rerolled?'spent':''}" data-die="${index}" aria-label="${E.classes[state.heroes[d.hero].classId].name} ${colorNames[d.color]} 주사위 ${d.value}${a?' · 기술 배치됨':''}" ${disabled?'disabled':''}>${content}<span class="die-tag">${['⚔','✦','◇'][d.color]} ${d.value}</span></button>`;
}
function skillCondition(t){return `${t.color===undefined?'모든 색':colorNames[t.color]} ${t.max?'1–'+t.max:(t.min||1)+'+'} · 에너지 ${t.energy}`;}
function renderBattle(){
 const b=state.battle,e=state.enemies.find(x=>x.id===b.enemy),it=E.intent(state),p=E.tacticalPreview(state);if(!busy)$('#battle-cue').textContent='';
 if(!b.participants.includes(battleHero)||state.heroes[battleHero].hp<=0)battleHero=b.participants.find(i=>state.heroes[i].hp>0)??b.participants[0];
 const h=state.heroes[battleHero],st=E.stats(h);
 $('#combat-title').textContent=`${demoMode?'전투 체험 · ':''}${e.name} · 교전 ${b.round}/8`;$('#retreat').disabled=busy||b.phase!=='plan';$('#demo-exit').hidden=!demoMode;
 $('#battle-enemy-card').innerHTML=`<span class="enemy-portrait enemy-${e.art}"></span><div class="enemy-vitals"><h3>${e.name} <small>갑옷 ${e.armor} · 저항 ${e.ward}</small></h3><div class="health-bar"><i style="width:${100*e.hp/e.max}%"></i><span>${e.hp} / ${e.max}</span></div></div><div class="intent"><span>다음 공격 · ${it.all?'전원':'전열'}</span><b>${it.name} · 피해 ${it.damage}</b><small>${it.desc}</small></div>`;
 $('#battle-hero-card').innerHTML=b.participants.map(i=>{const x=state.heroes[i],xs=E.stats(x);return `<button class="battle-hero ${i===battleHero?'selected':''}" data-battle-hero="${i}" ${x.hp<=0||busy?'disabled':''}><span class="portrait portrait-${portraits[x.classId]}"></span><strong>${E.classes[x.classId].name}</strong><span>♥ ${x.hp}/${xs.hp}</span><div class="health-bar"><i style="width:${100*x.hp/xs.hp}%"></i></div><small>에너지 ${x.energy}/4</small></button>`;}).join('');
 $('#tactics').innerHTML=`<div class="preparation"><span>${E.classes[h.classId].name} 준비</span>${Object.entries(stanceNames).map(([stance,name])=>button(name.split(' · ')[0],'stance',{hero:battleHero,stance},busy||b.phase!=='plan'||['focus','recover'].includes(stance)&&h.energy<1,`class="${b.stances[battleHero]===stance?'selected':''}" title="${name}"`)).join('')}</div>`;
 if(b.phase==='plan'){const total=b.participants.filter(i=>state.heroes[i].hp>0).reduce((a,i)=>E.pool(state,i,b.stances[i]).map((v,j)=>v+a[j]),[0,0,0]);$('#dice-tray').innerHTML=`<div class="pool-preview">${total.map((n,i)=>`<span class="${['red','blue','green'][i]}"><b>${['⚔','✦','◇'][i]}</b>${n}<small>${colorNames[i]}</small></span>`).join('')}<p>준비 태세를 고르고 아래에서 주사위를 굴리세요</p></div>`;}
 else $('#dice-tray').innerHTML=b.participants.map(i=>`<div class="dice-owner"><span>${E.classes[state.heroes[i].classId].name}</span><div>${b.dice.map((d,index)=>d.hero===i?dieMarkup(d,index):'').join('')}</div></div>`).join('');
 $('#dice-help').textContent=b.phase==='plan'?`강습: 공격 +1 · 집중: 에너지 1 / 마법 +2 · 방어: 방어 +2 · 회복: 에너지 1 / 파티 치유`:rerollMode?'재굴릴 주사위를 선택하세요 · 에너지 1 · 배치된 주사위는 취소 후 선택':chosenSkill?'빛나는 주사위를 터치해 선택한 기술에 배치하세요':'기술을 선택하고 주사위를 배치하세요 · 배치하지 않은 주사위는 기본 공격/방어';
 $('#reroll-mode').disabled=busy||b.phase!=='rolled';$('#reroll-mode').setAttribute('aria-pressed',String(rerollMode));$('#reroll-mode').textContent=rerollMode?'재굴림 모드 닫기':'재굴림 선택';
 $('#skill-cards').innerHTML=E.techniques[h.classId].filter(t=>E.level(h)>=(t.level||1)).map(t=>{const assigned=(b.assignments||[]).find(a=>a.owner===battleHero&&a.id===t.id),wait=Math.max(0,(b.cooldowns?.[battleHero+':'+t.id]||0)-b.round),possible=b.dice.some((d,index)=>!E.skillReason(state,battleHero,t.id,index,skillTarget??battleHero)),selected=chosenSkill===t.id;return `<article class="skill-card ${selected?'selected':''} ${assigned?'committed':''} ${wait?'cooldown':''}"><button class="skill-choice" data-skill="${t.id}" ${busy||wait||b.phase!=='rolled'?'disabled':''} aria-pressed="${selected}" aria-label="${t.name} · ${skillCondition(t)} · ${t.desc}"><span class="skill-art art-${t.art}" data-class="${h.classId}"></span><strong>${t.name}</strong><small class="skill-cost">${skillCondition(t)}</small><span class="skill-effect">${t.desc}</span><span class="skill-socket">${assigned?dieMarkup(b.dice[assigned.index],assigned.index,true):'<span>'+t.icon+'</span>'}</span><small>${wait?'대기 '+wait+'교전':assigned?'다시 눌러 배치 취소':b.phase==='plan'?'굴린 뒤 배치':possible?'배치 가능':'조건에 맞는 눈 없음'}</small></button></article>`;}).join('');
 const selected=chosenSkill&&E.technique(state,battleHero,chosenSkill);
 $('#combat-summary').innerHTML=b.phase==='rolled'?`<p class="eyebrow">예상 결과</p><strong>⚔ 피해 ${p.damage}</strong><span>◇ 방어 ${Object.values(p.blocks).reduce((a,n)=>a+n,0)} · ✚ 치유 ${Object.values(p.heals).reduce((a,n)=>a+n,0)}</span><small>반격 후 ${b.participants.filter(i=>state.heroes[i].hp>0).map(i=>E.classes[state.heroes[i].classId].name+' HP '+p.after[i]).join(' · ')}</small>${selected?.target?`<label>기술 대상<select id="skill-target" aria-label="기술 대상">${b.participants.filter(i=>state.heroes[i].hp>0).map(i=>`<option value="${i}" ${i===(skillTarget??battleHero)?'selected':''}>${E.classes[state.heroes[i].classId].name}</option>`).join('')}</select></label>`:''}`:`<p class="eyebrow">전략 준비</p><strong>적의 다음 공격을 확인하세요</strong><small>${state.lastResult?esc(state.lastResult.title):'낮은 눈도 보호·지원 기술에 활용할 수 있습니다.'}</small>`;
 $('#roll').disabled=busy||b.phase!=='plan';$('#resolve').disabled=busy||b.phase!=='rolled';$('#battle-action-note').textContent=b.phase==='plan'?'기술 세 장으로 공격과 생존을 선택하세요. 레벨 3에는 강력한 기술이 해금됩니다.':`배치 ${b.assignments?.length||0}개 · 에너지 소비는 실행 시 확정 · 기술을 쓰지 않고 실행할 수도 있습니다.`;
}
function gearArt(id){const g=E.gear[id];return `<svg class="item-art item-${g.slot}" viewBox="0 0 100 100" role="img" aria-label="${g.name}"><svg width="100" height="100" viewBox="${id%4*100} ${Math.floor(id/4)*100} 100 100" overflow="hidden"><image href="assets/gear.png" width="400" height="300" preserveAspectRatio="none"/></svg></svg>`;}
function openVictory(){lootQuest=null;lootChoice=null;$('#loot-confirm').disabled=false;$('#loot-eyebrow').textContent=demoMode?'BATTLE REHEARSAL':'VICTORY & GROWTH';$('#loot-title').textContent='전투 승리';$('#loot-text').textContent=state.lastResult.text;$('#loot-cards').innerHTML=`<article class="victory-trophy">◆<h3>${demoMode?'첫 전투를 마쳤습니다':'봉인 '+state.seals+' / 3'}</h3><p>${demoMode?'다른 주사위 배치로 다시 도전해 보세요.':'성장과 장비를 준비해 다음 지역에 도전하세요.'}</p></article>`;$('#loot-confirm').textContent=demoMode?'체험 마치고 돌아가기':'지도에서 모험 계속';$('#loot').showModal();}
function openQuestReward(id){const q=E.quests.find(q=>q.id===id);lootQuest=id;lootChoice=null;$('#loot-eyebrow').textContent='CHOOSE YOUR REWARD';$('#loot-title').textContent=q.name+' · 보상';$('#loot-text').textContent=`경험치 +${q.xp} · 골드 +${q.gold} · 장비 하나를 선택하세요`;$('#loot-cards').innerHTML=q.choices.map(id=>{const g=E.gear[id],current=E.hero(state).equipment[g.slot];return `<button class="reward-card" data-reward="${id}">${gearArt(id)}<small>${slotNames[g.slot]}</small><h3>${g.name}</h3><p>${g.desc}</p><div class="compare">현재 장비<br>${current===null?'비어 있음':E.gear[current].name+' · '+E.gear[current].desc}</div></button>`;}).join('');$('#loot-confirm').disabled=true;$('#loot-confirm').textContent='장비 선택 후 확정';$('#sheet').close();folio=null;$('#loot').showModal();}
function openFolio(kind,index=state?.active||0){folio={kind,index,tab:kind==='hero'?'equipment':kind==='travel'&&inspected&&inspected!==E.hero(state).pos&&!E.routes.some(r=>r.a===E.hero(state).pos&&r.b===inspected||r.b===E.hero(state).pos&&r.a===inspected)?'plan':'active'};renderFolio();if(!$('#sheet').open)$('#sheet').showModal();}
function renderFolio(){const scroll=$('#sheet').scrollTop,focusId=document.activeElement?.dataset?.focus;$('#sheet-eyebrow').textContent=({quests:'QUEST JOURNAL',hero:'HERO FOLIO',shop:'TRADING POST',rules:'CAMPAIGN RULES',log:'CHRONICLE',travel:'JOURNEY PLANNER'})[folio.kind];$('#sheet-title').textContent=({quests:'퀘스트 일지',hero:'장비와 직업 특성',shop:'거점의 상점',rules:'잿빛 왕국의 영웅들',log:'모험 기록',travel:'여행 계획'})[folio.kind];$('#sheet-content').innerHTML=folio.kind==='travel'?travelFolio():folio.kind==='quests'?questFolio():folio.kind==='hero'?heroFolio():folio.kind==='shop'?shopFolio():folio.kind==='log'?`<ol class="log-list">${state.log.map(t=>`<li>${esc(t)}</li>`).join('')}</ol>`:rulesFolio();$('#sheet').scrollTop=scroll;if(focusId)document.querySelector(`[data-focus="${focusId}"]`)?.focus({preventScroll:true});}
function questFolio(){const h=E.hero(state),can=!state.battle&&!state.outcome,inTown=E.town(h.pos),qstatus=q=>h.completed.includes(q.id)?'completed':h.quests.some(x=>x.id===q.id)?'active':'available';const list=E.quests.filter(q=>qstatus(q)===folio.tab);
 return `<p class="sheet-note">${E.classes[h.classId].name} · 수락 ${h.quests.length}/3 · 보고는 어느 거점에서든 행동 1개.<br>퀘스트 수락은 거점에서 무료. 수집·호위·사냥 중 경로와 보상을 골라 성장하세요.</p><div class="folio-tabs">${[['active','진행 중'],['available','새 퀘스트'],['completed','완료']].map(([id,label])=>`<button data-tab="${id}" class="${folio.tab===id?'active':''}">${label}</button>`).join('')}</div>${list.length?list.map(q=>{const own=h.quests.find(x=>x.id===q.id),complete=qstatus(q)==='completed';return `<article class="quest-card"><h3>${q.name}<span class="badge">Lv.${q.level} · ${{gather:'탐사',escort:'호위',hunt:'사냥'}[q.type]}</span></h3><p>${q.desc}</p><p>목적지 ${locationName(q.pos)} ${q.pos}${own?.ready?' · ✓ 목표 달성':''}</p><p class="rewards">경험치 +${q.xp} · 골드 +${q.gold} · 장비 1개 선택</p>${complete?'<p>✓ 보상 수령 완료</p>':own?`${own.ready?`<button data-claim="${q.id}" ${!can||!inTown||state.actions<1?'disabled':''}>보상 카드 비교 · 거점 보고</button>`:`<button data-pin="${q.id}">지도에 목표 표시</button>`}${button('포기','abandon',{id:q.id},!can)}`:button(levelText(h,q),'accept',{id:q.id},!can||!inTown||E.level(h)<q.level||h.quests.length>=3||q.id==='caravan'&&(h.pos!=='C5'||h.supply<1)||q.type==='hunt'&&state.enemies.find(e=>e.pos===q.pos).hp===0&&!h.kills.includes(state.enemies.find(e=>e.pos===q.pos).id))}</article>`;}).join(''):'<p class="sheet-note">이 목록에 퀘스트가 없습니다. 새 퀘스트를 살펴보세요.</p>'}`;
}
function levelText(h,q){if(q.type==='hunt'){const e=state.enemies.find(e=>e.pos===q.pos);if(e.hp===0&&!h.kills.includes(e.id))return '다른 영웅이 해결한 지역';}return E.level(h)<q.level?'레벨 '+q.level+'부터 수락':q.id==='caravan'?'마을에서 보급 1로 수락':'거점에서 수락';}
function heroFolio(){const h=state.heroes[folio.index],c=E.classes[h.classId],st=E.stats(h),own=folio.index===state.active,can=own&&!state.battle&&!state.outcome&&h.hp>0;return `<div class="hero-folio-head"><span class="portrait portrait-${portraits[h.classId]}"></span><div><h3>${c.name} · Lv.${E.level(h)}</h3><p>${c.role}<br>HP ${h.hp}/${st.hp} · 에너지 ${h.energy}/4 · XP ${h.xp}${E.level(h)<4?' / 다음 레벨 '+[0,2,6,12][E.level(h)]:''}<br>골드 ${h.gold} · 보급 ${h.supply} · 치유 물약 ${h.potions}</p></div></div><div class="technique-list"><p class="eyebrow">직업 기술 · 주사위 배치</p>${E.techniques[h.classId].map(t=>`<span class="${E.level(h)<(t.level||1)?'locked':''}"><b>${t.name}</b> ${t.level?'Lv.'+t.level+' · ':''}${t.desc}</span>`).join('')}</div><div class="build-stats"><span>공격 <b>${st.red}</b></span><span>마법 <b>${st.blue}</b></span><span>방어 <b>${st.green}</b></span><span>갑옷 <b>${st.armor}</b></span><span>치명타 <b>+${st.crit}</b></span></div><div class="folio-tabs"><button data-tab="equipment" class="${folio.tab==='equipment'?'active':''}">장비 · 가방</button><button data-tab="talents" class="${folio.tab==='talents'?'active':''}">직업 특성 ${h.points?'('+h.points+')':''}</button><button data-sheet="log">모험 기록</button></div>${folio.tab==='talents'?`<p class="sheet-note">${c.paths.join(' / ')} · 남은 특성 포인트 ${h.points}<br>레벨 2·3·4마다 두 특성 중 하나 선택. 선택은 캠페인 동안 유지됩니다.</p><div class="talent-grid">${E.talents[h.classId].map((t,i)=>{const learned=h.talents.includes(i),locked=h.talents.some(id=>E.talents[h.classId][id].tier===t.tier);return `<article class="talent-card ${learned?'learned':''}"><p>Lv.${t.tier} · ${t.path}</p><h3>${t.name}</h3><p>${t.desc}</p>${button(learned?'✓ 배운 특성':locked?'다른 특성 선택됨':'특성 선택','talent',{index:i},!can||h.points<1||E.level(h)<t.tier||locked)}</article>`;}).join('')}</div>`:`<div class="equipment-slots">${Object.entries(slotNames).map(([slot,name])=>`<div><small>${name}</small>${h.equipment[slot]===null?'비어 있음':E.gear[h.equipment[slot]].name}</div>`).join('')}</div><p class="sheet-note">장비는 소모되지 않습니다. 같은 슬롯은 하나만 착용하며 교체는 전투 밖에서 무료입니다.${!own?' 현재 차례의 영웅만 변경할 수 있습니다.':''}</p>${button('치유 물약 사용 · HP +6 / 행동 1','potion',{},!can||h.potions<1||h.hp===st.hp||state.actions<1)}<div class="gear-grid" style="margin-top:15px">${[...new Set(h.bag)].map(id=>gearCard(id,h,can)).join('')||'<p class="sheet-note">가방이 비어 있습니다. 퀘스트 보상이나 상점에서 장비를 구하세요.</p>'}</div>`}`;}
function gearCard(id,h,can){const g=E.gear[id],equipped=h.equipment[g.slot]===id;return `<article class="gear-card ${equipped?'equipped':''}">${gearArt(id)}<p>${slotNames[g.slot]} · ${['','일반','희귀','영웅'][g.tier]}</p><h3>${g.name}</h3><p>${g.desc}</p>${button(equipped?'✓ 착용 중':'장착','equip',{id},!can||equipped)}${state.heroes.map((x,i)=>x!==h&&x.pos===h.pos&&x.hp>0?button(E.classes[x.classId].name+'에게 전달 · 행동 1','trade',{id,hero:i},!can||state.actions<1):'').join('')}</article>`;}
function shopFolio(){const h=E.hero(state),can=E.town(h.pos)&&!state.battle&&!state.outcome&&state.actions>0;return `<p class="sheet-note">${locationName(h.pos)} · 보유 골드 ${h.gold} · Lv.${E.level(h)}<br>${E.town(h.pos)?'구매마다 행동 1개. 구매한 장비는 「영웅」에서 장착하세요.':'마을·야영지·항구에 도착하면 구매할 수 있습니다.'}</p><div class="gear-grid"><article class="gear-card"><h3>여행 보급 ×2</h3><p>야영·호위·유적 탐사에 사용</p>${button('1 골드 · 구매','buy',{id:'supply'},!can||h.gold<1)}</article><article class="gear-card"><h3>치유 물약</h3><p>전투 밖에서 행동 1로 체력 +6</p>${button('2 골드 · 구매','buy',{id:'potion'},!can||h.gold<2)}</article>${E.gear.map((g,id)=>`<article class="gear-card"><p>${slotNames[g.slot]} · Lv.${g.tier}</p><h3>${g.name}</h3><p>${g.desc}</p>${button(`${g.cost} 골드 · 구매`,'buy',{id},!can||h.gold<g.cost||E.level(h)<g.tier)}</article>`).join('')}</div>`;}
function rulesFolio(){return `<article class="rule-block"><h3>기술 배치 전투</h3><p>준비 → 굴림 → 기술 선택 → 주사위 배치 → 실행. 배치한 주사위는 기본 공격에서 빠집니다. 기술의 색·눈·에너지 조건을 확인하세요. 배치는 실행 전 취소할 수 있습니다. 재굴림 선택을 켜면 에너지 1로 주사위를 다시 굴립니다. 대기 1 기술은 다음 교전에는 쉬고 그다음 교전에 돌아옵니다. 레벨 3에 네 번째 기술이 해금됩니다. 보호는 출혈에 무시되지만 적 공격 감소는 적용됩니다.</p></article><p class="sheet-note">2005년 월드 오브 워크래프트 보드게임의 여행·퀘스트·장비·직업 성장에서 영감을 받은 자체 협동 캠페인입니다. 엘더폴의 독자 규칙이며, 여기서는 진영 간 경쟁 대신 공동 레이드를 진행합니다.</p>${[
 ['1 · 캠페인의 목표','20라운드 안에 D1 잿빛 용을 처치하세요. 가시늑대·트롤·망령 기사 중 2종을 처치해 봉인 2개를 모으고 현재 영웅 레벨 3이 되면 용에 도전할 수 있습니다. 세 번째 봉인도 모으면 용의 체력이 6 감소합니다. 모든 영웅이 쓰러지거나 20라운드가 끝나면 패배합니다.'],
 ['2 · 여행과 차례','도로·다리·고개로 연결된 지역만 이동합니다. 지역을 터치해 경로 비용을 확인하고 왼쪽 아래 이동 확정 버튼을 누르세요. 여행 계획에서는 거점과 목표까지의 우회로도 비교할 수 있습니다. 각 길의 행동·보급·체력 비용이 다릅니다. 강과 산은 연결된 길로만 건널 수 있습니다. 혼자면 차례당 행동 4개, 2~4명이면 영웅별 3개. 남은 행동이 없어도 장비·특성을 관리할 수 있습니다. 전체 차례가 끝나면 라운드가 증가하고 시작 영웅이 순환합니다.'],
 ['여행 계획 · 안전과 지름길','동부 가도에서 광산으로 가는 급류 여울은 행동 1·보급 1·체력 2. 항구를 경유한 해안 우회로는 행동 3으로 이동 피해가 없습니다. 고개는 레벨 2부터 오를 수 있고 제단·북쪽 고개는 행동 2·보급 1. 더 높은 난이도의 지역으로 진입할 때 현재 레벨이 낮으면 부족한 레벨마다 추가 체력 피해 2. 같은 난이도나 낮은 지역으로 돌아갈 때는 추가 피해가 없습니다. 늑대의 북쪽 통로, 트롤의 유적 계단, 망령의 용 회랑은 해당 지역 적을 처치해야 앞으로 통과할 수 있습니다. 되돌아오는 길은 열려 있습니다. 용의 둥지는 봉인 2개와 현재 레벨 3부터 진입.'],
 ['3 · 퀘스트와 보상','거점(마을 C5, 야영지 A4, 항구 E5)에서 무료로 최대 3개까지 수락합니다. 수집은 목적지에서 지역 조사, 호위는 보급 1을 내고 목적지에 도달, 사냥은 해당 전투에 참여해 승리해야 합니다. 이미 잡은 적의 퀘스트도 보고할 수 있습니다. 목표 달성 후 어느 거점에서든 행동 1로 보고하고 영웅 개인이 경험치·골드·선택 장비를 받습니다.'],
 ['4 · 장비와 특성','경험치 2/6/12에 레벨 2/3/4. 레벨마다 체력 +2와 특성 포인트 1. 각 레벨의 직업 특성 두 개 중 하나를 선택합니다. 장비는 무기·갑옷·장신구 각 하나. 교체는 전투 밖에서 무료이며 사용해도 사라지지 않습니다. 공격/마법/방어 주사위, 갑옷, 치명타, 재굴림, 회복을 조합하세요.'],
 ['5 · 주사위 전투','전투 시작은 행동 1. 같은 지역의 살아 있는 영웅이 모두 참여합니다. 참여 인원에 따라 적의 체력이 늘어나며, 이 체력은 후퇴해도 유지됩니다. 영웅별로 강습(공격 +1), 집중(에너지 1로 마법 +2), 방어(방어 +2), 회복(에너지 1로 방어 +1과 참여 영웅 전원 치유)을 선택하세요. 준비 후 함께 굴립니다.'],
 ['6 · 결과와 반격','공격 주사위 4·5·6은 피해 2. 마법 주사위 3·4·5는 피해 1, 6은 피해 2. 치명타 수치는 공격/마법 6에 추가됩니다. 방어 주사위 4·5·6은 해당 영웅 방어 2. 「재굴림 선택」에서 주사위를 선택해 에너지 1로 재굴림할 수 있으며 기본 한도는 영웅당 교전마다 1개입니다. 물리 총합에서 갑옷, 마법 총합에서 마법 저항을 각각 뺍니다. 피해→회복→적 반격 순서. 적을 처치하면 반격이 없습니다.'],
 ['7 · 전열과 적의 의도','받는 피해 감소(갑옷+방어 성공)가 가장 높은 살아 있는 영웅이 단일 공격을 받습니다. 동률은 참여 순서. 용의 화염 숨결은 전원을 공격합니다. 출혈은 방어 주사위를 무시하지만 갑옷은 적용됩니다. 트롤은 특정 공격 후 체력 2 재생, 망령의 저주는 에너지 1 감소. 용은 체력 절반 이하에서 공격 +2.'],
 ['8 · 회복·후퇴·세계 사건','에너지는 최대 4, 자신의 차례가 시작되면 +1. 거점 휴식은 체력 +6·에너지 +2, 야영은 보급 1로 체력 +3·에너지 +2. 물약은 전투 밖에서 체력 +6. 준비 단계에 후퇴하면 참여 영웅이 체력 2(최소 1 남음)를 잃고 마을로 귀환하며 남은 행동을 포기합니다. 교전 8회 후에도 승리하지 못하면 마을로 철수합니다. 3라운드마다 세계 사건이 발생합니다.'],
 ['9 · 쓰러짐과 저장','다른 영웅이 살아 있으면 쓰러진 영웅은 다음 차례에 마을에서 체력 4로 부활하고 그 차례를 쉽니다. 전투 파티 전원이 쓰러졌지만 다른 영웅이 살아 있다면 해당 파티는 마을로 귀환합니다. 이 브라우저에 자동 저장하며 이전 v0.4 기록은 별도로 보존합니다. 온라인·기기 간 동기화는 제공하지 않습니다.']
 ].map(([title,text])=>`<article class="rule-block"><h3>${title}</h3><p>${text}</p></article>`).join('')}`;}
document.addEventListener('click',event=>{const b=event.target.closest('button');if(!b||b.disabled||busy)return;if(b.dataset.battleHero!==undefined){battleHero=Number(b.dataset.battleHero);chosenSkill=null;skillTarget=battleHero;renderBattle();return;}if(b.dataset.skill){if((state.battle.assignments||[]).some(a=>a.owner===battleHero&&a.id===b.dataset.skill)){chosenSkill=null;act('unassign',{owner:battleHero,id:b.dataset.skill});return;}chosenSkill=chosenSkill===b.dataset.skill?null:b.dataset.skill;rerollMode=false;skillTarget=battleHero;renderBattle();return;}if(b.dataset.die!==undefined){const index=Number(b.dataset.die);if(rerollMode)act('reroll',{index});else if(chosenSkill)act('assign',{owner:battleHero,id:chosenSkill,index,target:skillTarget??battleHero});else message('먼저 사용할 기술 카드를 선택하세요. 재굴림은 재굴림 선택 버튼을 누르세요.');return;}if(b.dataset.reward!==undefined){lootChoice=Number(b.dataset.reward);document.querySelectorAll('[data-reward]').forEach(el=>el.classList.toggle('selected',Number(el.dataset.reward)===lootChoice));$('#loot-confirm').disabled=false;$('#loot-confirm').textContent='선택 확정 · 퀘스트 보고';return;}if(b.dataset.action){const trip=b.dataset.travel;act(b.dataset.action,JSON.parse(b.dataset.arg||'{}'));if(trip&&state&&E.hero(state).pos===JSON.parse(b.dataset.arg).pos){$('#sheet').close();folio=null;}}else if(b.dataset.sheet){if(state||b.dataset.sheet==='rules')openFolio(b.dataset.sheet);}else if(b.dataset.inspect!==undefined)openFolio('hero',Number(b.dataset.inspect));else if(b.dataset.tab){folio.tab=b.dataset.tab;renderFolio();}else if(b.dataset.pin){pinned=b.dataset.pin;$('#sheet').close();folio=null;render();}else if(b.dataset.claim)openQuestReward(b.dataset.claim);});
document.addEventListener('change',event=>{if(event.target.id==='skill-target'){skillTarget=Number(event.target.value);renderBattle();}});
$('#reroll-mode').addEventListener('click',()=>{if(busy)return;rerollMode=!rerollMode;chosenSkill=null;renderBattle();});
$('#fast-motion').addEventListener('click',()=>{fastMotion=!fastMotion;$('#fast-motion').setAttribute('aria-pressed',String(fastMotion));});
$('#loot-close').addEventListener('click',()=>{$('#loot').close();lootQuest=null;});
$('#loot-confirm').addEventListener('click',async()=>{if(lootQuest){if(await act('claim',{id:lootQuest,gear:lootChoice})){$('#loot').close();lootQuest=null;}}else{$('#loot').close();if(demoMode)exitDemo();}});
function startDemo(){if(busy)return;campaignBeforeDemo=state?JSON.parse(JSON.stringify(state)):null;demoMode=true;state=E.create([0]);E.hero(state).pos='A2';E.hero(state).hp=9;state.enemies[0].hp=state.enemies[0].max=14;E.apply(state,'engage');battleHero=0;skillTarget=0;chosenSkill=null;rerollMode=false;resultDismissed=false;render();message('전투 체험 · 적 공격 확인 → 굴림 → 기술 카드 → 주사위 배치 → 실행');}
function exitDemo(){if(busy)return;$('#loot').close();$('#result').close();state=campaignBeforeDemo;campaignBeforeDemo=null;demoMode=false;chosenSkill=null;rerollMode=false;resultDismissed=false;render();}
$('#demo').addEventListener('click',startDemo);$('#try-battle').addEventListener('click',startDemo);$('#demo-exit').addEventListener('click',exitDemo);
$('#start').addEventListener('click',()=>{try{state=E.create([...$('#class-picker').querySelectorAll('input:checked')].map(x=>Number(x.value)));pinned=null;inspected=null;resultDismissed=false;persist();render();}catch(e){$('#setup-error').textContent=e.message;}});
$('#explore').addEventListener('click',()=>$('#explore').dataset.travelTo?act('move',{pos:$('#explore').dataset.travelTo}):act('explore'));
for(const id of ['engage','rest','roll','resolve'])$('#'+id).addEventListener('click',()=>act(id));$('#end-turn').addEventListener('click',()=>act('end'));$('#retreat').addEventListener('click',()=>act('retreat'));
function restart(){if(demoMode){exitDemo();return;}if(confirm('이 캠페인을 종료하고 새 영웅을 선택할까요?')){$('#sheet').close();$('#result').close();folio=null;state=null;try{localStorage.setItem(SAVE,'null');}catch{}resultDismissed=false;render();}}
$('#new-game').addEventListener('click',restart);$('#result-new').addEventListener('click',restart);$('#close-sheet').addEventListener('click',()=>{$('#sheet').close();folio=null;});$('#sheet').addEventListener('close',()=>{folio=null;});$('#result-close').addEventListener('click',()=>{resultDismissed=true;$('#result').close();});$('#result').addEventListener('cancel',()=>{resultDismissed=true;});
try{const value=localStorage.getItem(SAVE)||localStorage.getItem('elderfall-campaign-v2');if(value&&value!=='null'){const old=JSON.parse(value),saved=E.upgradeMap(old);if(!E.validate(saved))throw Error('invalid');state=saved;if(!localStorage.getItem(SAVE))persist();if(old.mapVersion===undefined){try{if(!localStorage.getItem('elderfall-campaign-v2-before-routes'))localStorage.setItem('elderfall-campaign-v2-before-routes',value);}catch{storageAvailable=false;}persist();message('새 지역 지도 적용 · 기존 성장과 장비를 유지했습니다.');}}}catch{state=null;$('#setup-error').textContent='캠페인 기록을 읽지 못했습니다. 새 캠페인을 시작할 수 있습니다.';}
render();
