'use strict';
const assert=require('node:assert/strict');
const E=require('../game-engine.js');
const high=()=>0.999999,low=()=>0;
let checks=0;
function test(name,fn){fn();checks++;console.log('PASS',name);}
function next(s){if(!s.actions)E.apply(s,'end');}
function move(s,pos){next(s);E.apply(s,'move',{pos});}
function clear(s,pos){while(s.enemies.some(e=>e.hp>0&&e.pos===pos)){next(s);E.apply(s,'attack',{pos},high);while(s.pending.length)E.apply(s,'award',{hero:0});}}
test('1–4 player scaling and invalid party rejection',()=>{for(let p=1;p<=4;p++){let s=E.create(Array.from({length:p},(_,i)=>i));assert.equal(s.actions,p===1?4:3);assert.equal(s.enemies[0].hp,3+p);}assert.throws(()=>E.create([]));assert.throws(()=>E.create([0,0]));});
test('Invalid movement/attack does not spend actions',()=>{let s=E.create([0]);assert.throws(()=>E.apply(s,'move',{pos:'C3'}));assert.throws(()=>E.apply(s,'attack',{pos:'A2'}));assert.equal(s.actions,4);assert.equal(E.hero(s).pos,'C5');});
test('Natural six adds damage; missed attack spends action',()=>{let s=E.create([3]);E.hero(s).pos='D1';s.enemies.push({name:'test',pos:'D1',hp:10,max:10,def:4,boss:true});E.apply(s,'attack',{pos:'D1'},low);assert.equal(s.actions,3);assert.equal(s.enemies[3].hp,10);E.apply(s,'attack',{pos:'D1'},high);assert.equal(s.enemies[3].hp,8);});
test('Camp kill gives shared XP, seal and two one-time rewards',()=>{let s=E.create([0,1]);E.hero(s).pos='A2';s.enemies[0].hp=1;E.apply(s,'attack',{pos:'A2'},high);assert.equal(s.seals,1);assert.deepEqual(s.heroes.map(h=>h.xp),[1,1]);assert.equal(s.pending.length,2);assert.throws(()=>E.apply(s,'end'));E.apply(s,'award',{hero:1});E.apply(s,'award',{hero:0});assert.equal(s.pending.length,0);assert.equal(s.deck.length,4);});
test('Healing caps HP and cannot revive; skill limited per turn',()=>{let s=E.create([3,0]);s.heroes[1].hp=9;E.apply(s,'skill',{hero:1});assert.equal(s.heroes[1].hp,10);assert.throws(()=>E.apply(s,'skill',{hero:1}));let t=E.create([3,0]);t.heroes[1].hp=0;assert.throws(()=>E.apply(t,'skill',{hero:1}));assert.equal(t.actions,3);});
test('Archer ranged attack and mage guaranteed damage',()=>{let s=E.create([2]);E.hero(s).pos='A3';E.apply(s,'skill',{pos:'A2'},high);assert.equal(s.enemies[0].hp,1);let t=E.create([1]);E.hero(t).pos='A2';E.apply(t,'skill',{pos:'A2'});assert.equal(t.enemies[0].hp,2);});
test('Guard takes priority over shield and shield auto blocks next attack',()=>{let s=E.create([0]);E.hero(s).pos='A2';E.hero(s).items=[3];E.apply(s,'skill');E.apply(s,'end');assert.equal(E.hero(s).hp,10);assert.deepEqual(E.hero(s).items,[3]);E.apply(s,'end');assert.equal(E.hero(s).hp,10);assert.deepEqual(E.hero(s).items,[]);E.apply(s,'end');assert.equal(E.hero(s).hp,8);});
test('Ordinary enemy attacks highest HP; next-round leader rotates',()=>{let s=E.create([0,1]);s.heroes.forEach(h=>h.pos='A2');E.apply(s,'end');E.apply(s,'end');assert.equal(s.heroes[0].hp,8);assert.equal(s.heroes[1].hp,7);assert.equal(s.round,2);assert.equal(s.active,1);});
test('Fallen hero revives at village and loses whole turn',()=>{let s=E.create([0,1]);s.heroes[1].hp=0;E.apply(s,'end');assert.equal(s.heroes[1].hp,4);assert.equal(s.heroes[1].pos,'C5');assert.equal(s.actions,0);assert.throws(()=>E.apply(s,'rest'));});
test('Party wipe and time limit both lose',()=>{let s=E.create([0]);E.hero(s).pos='A2';E.hero(s).hp=2;E.apply(s,'end');assert.equal(s.outcome,'lose');let t=E.create([0]);for(let i=0;i<10;i++)E.apply(t,'end');assert.equal(t.outcome,'lose');assert.equal(t.round,10);});
test('Loot consumption, boots range, and same-tile trade',()=>{let s=E.create([0,1]);E.hero(s).items=[0,2,5];E.hero(s).hp=4;E.apply(s,'item',{index:0});assert.equal(E.hero(s).hp,8);E.apply(s,'item',{index:0,pos:'C3'});assert.equal(E.hero(s).pos,'C3');assert.throws(()=>E.apply(s,'trade',{index:0,hero:1}));s.heroes[1].pos='C3';E.apply(s,'trade',{index:0,hero:1});assert.deepEqual(s.heroes[1].items,[5]);});
test('Boss requires seals, attacks whole tile, and ends immediately on kill',()=>{let s=E.create([0,1]);s.heroes.forEach(h=>h.pos='D1');assert.throws(()=>E.apply(s,'summon'));s.seals=3;E.apply(s,'summon');assert.equal(s.enemies[3].hp,14);E.apply(s,'end');E.apply(s,'end');assert.deepEqual(s.heroes.map(h=>h.hp),[8,5]);s.enemies[3].hp=1;E.apply(s,'skill',{pos:'D1'});assert.equal(s.outcome,'win');assert.throws(()=>E.apply(s,'end'));});
test('Complete solo campaign through real actions',()=>{let s=E.create([0],high);for(const pos of ['B5','A5','A4','A3','A2'])move(s,pos);clear(s,'A2');for(const pos of ['B2','B1'])move(s,pos);clear(s,'B1');for(const pos of ['C1','D1','E1','E2','E3'])move(s,pos);clear(s,'E3');for(const pos of ['D3','D2','D1'])move(s,pos);next(s);E.apply(s,'summon');clear(s,'D1');assert.equal(s.outcome,'win');assert.ok(s.round<=10);assert.equal(s.seals,3);assert.equal(E.hero(s).xp,3);assert.equal(s.deck.length,0);assert.equal(E.hero(s).items.length,5);assert.ok(!E.hero(s).items.includes(3));});
test('Enemy damage report survives same-phase resurrection',()=>{let s=E.create([0,1]);s.heroes[1].pos='A2';s.heroes[1].hp=1;E.apply(s,'end');E.apply(s,'end');assert.equal(s.lastEnemyDamage,1);assert.equal(s.heroes[1].hp,4);assert.equal(s.actions,0);});
console.log(`PASS: ${checks} engine scenarios`);
