'use strict';
const assert=require('node:assert/strict'),E=require('../game-engine.js');
const high=()=>.999999,low=()=>0;let count=0;
function test(name,fn){fn();count++;console.log('PASS',name);}
function full(s){for(const h of s.heroes){h.hp=E.stats(h).hp;h.energy=4;}}
function fight(s,id,stance='assault',random=high){const e=s.enemies.find(e=>e.id===id);E.hero(s).pos=e.pos;E.apply(s,'engage');while(s.battle){for(const i of s.battle.participants.filter(i=>s.heroes[i].hp>0))E.apply(s,'stance',{hero:i,stance:['focus','recover'].includes(stance)&&s.heroes[i].energy<1?'assault':stance});E.apply(s,'roll',{},random);E.apply(s,'resolve');}}
function action(s,type,arg={},random=high){if(!s.actions)E.apply(s,'end');E.apply(s,type,arg,random);}
function walk(s,pos){while(E.hero(s).pos!==pos){const h=E.hero(s);const next=h.pos[0]!==pos[0]?String.fromCharCode(h.pos.charCodeAt(0)+(h.pos[0]<pos[0]?1:-1))+h.pos[1]:h.pos[0]+(Number(h.pos[1])+(h.pos[1]<pos[1]?1:-1));const cost=E.locations[next]?.kind==='mountain'?2:1;if(s.actions<cost)E.apply(s,'end');E.apply(s,'move',{pos:next});}}
test('Distinct classes, 1–4 players, save version and initial resources',()=>{for(let n=1;n<=4;n++){const s=E.create(Array.from({length:n},(_,i)=>i));assert.equal(s.version,2);assert.equal(s.actions,n===1?4:3);assert.ok(E.validate(s));assert.equal(s.heroes[0].quests[0].id,'herbs');}assert.throws(()=>E.create([]));assert.throws(()=>E.create([0,0]));assert.notDeepEqual(E.classes[0].pool,E.classes[1].pool);});
test('Rejected actions never spend resources',()=>{const s=E.create([0]),before=JSON.stringify(s);for(const [type,arg] of [['move',{pos:'C3'}],['engage',{}],['explore',{}],['claim',{id:'herbs',gear:0}],['talent',{index:0}]]){assert.throws(()=>E.apply(s,type,arg));assert.equal(JSON.stringify(s),before);}});
test('Mountain entry costs two actions and cannot overspend',()=>{const s=E.create([0]);E.hero(s).pos='C4';s.actions=1;assert.throws(()=>E.apply(s,'move',{pos:'C3'}));assert.equal(E.hero(s).pos,'C4');s.actions=2;E.apply(s,'move',{pos:'C3'});assert.equal(s.actions,0);});
test('Gather, report and personal reward choice unlock level and talent',()=>{const s=E.create([0,1]);E.apply(s,'move',{pos:'C4'});E.apply(s,'explore');assert.equal(s.heroes[0].quests[0].ready,true);assert.throws(()=>E.apply(s,'claim',{id:'herbs',gear:0}));E.apply(s,'move',{pos:'C5'});E.apply(s,'end');E.apply(s,'end');E.apply(s,'end');E.apply(s,'claim',{id:'herbs',gear:0});assert.equal(s.heroes[0].xp,2);assert.equal(s.heroes[1].xp,0);assert.equal(s.heroes[0].points,1);assert.equal(s.heroes[0].gold,7);assert.deepEqual(s.heroes[0].bag,[0]);assert.throws(()=>E.apply(s,'claim',{id:'herbs',gear:0}));});
test('Quests require town, level and capacity; repeated rewards blocked',()=>{const s=E.create([0]);assert.throws(()=>E.apply(s,'accept',{id:'mine'}));E.apply(s,'accept',{id:'caravan'});E.apply(s,'accept',{id:'wolves'});assert.equal(E.hero(s).quests.length,3);assert.throws(()=>E.apply(s,'accept',{id:'wolves'}));E.apply(s,'abandon',{id:'wolves'});E.hero(s).pos='C4';assert.throws(()=>E.apply(s,'accept',{id:'wolves'}));});
test('Escort consumes supply and completes at the correct town',()=>{const s=E.create([0]);E.apply(s,'accept',{id:'caravan'});assert.equal(E.hero(s).supply,1);E.hero(s).pos='B4';E.apply(s,'move',{pos:'A4'});assert.equal(E.hero(s).quests.find(q=>q.id==='caravan').ready,true);});
test('Exploration costs energy or supply and not a free repeat',()=>{const s=E.create([1]);E.hero(s).xp=2;E.apply(s,'accept',{id:'relic'});E.hero(s).pos='C2';E.hero(s).energy=1;assert.throws(()=>E.apply(s,'explore'));E.hero(s).energy=2;E.apply(s,'explore');assert.equal(E.hero(s).energy,0);assert.throws(()=>E.apply(s,'explore'));});
test('Talents force one choice at each tier and persist in stats',()=>{const s=E.create([0]),h=E.hero(s);h.xp=6;h.points=2;E.apply(s,'talent',{index:0});assert.equal(E.stats(h).red,3);assert.throws(()=>E.apply(s,'talent',{index:1}));E.apply(s,'talent',{index:3});assert.equal(E.stats(h).armor,1);assert.equal(h.points,0);assert.throws(()=>E.apply(s,'talent',{index:4}));});
test('Persistent gear, slot replacement and combat equipment lock',()=>{const s=E.create([0]),h=E.hero(s);h.bag=[0,1,2];E.apply(s,'equip',{id:0});assert.equal(E.stats(h).red,3);E.apply(s,'equip',{id:1});assert.equal(E.stats(h).red,2);assert.equal(E.stats(h).blue,1);assert.deepEqual(h.bag,[0,1,2]);h.pos='A2';E.apply(s,'engage');assert.throws(()=>E.apply(s,'equip',{id:2}));});
test('Shop enforces funds, level and town and costs one action',()=>{const s=E.create([0]);E.apply(s,'buy',{id:0});assert.equal(E.hero(s).gold,0);assert.equal(s.actions,3);assert.throws(()=>E.apply(s,'buy',{id:1}));E.hero(s).gold=99;assert.throws(()=>E.apply(s,'buy',{id:10}));E.hero(s).pos='C4';assert.throws(()=>E.apply(s,'buy',{id:'supply'}));});
test('Rest uses supply outdoors, caps HP and energy; potion is consumed',()=>{const s=E.create([0]),h=E.hero(s);h.pos='C4';h.hp=1;h.energy=0;E.apply(s,'rest');assert.equal(h.hp,4);assert.equal(h.energy,2);assert.equal(h.supply,1);E.apply(s,'potion');assert.equal(h.hp,10);assert.equal(h.potions,0);h.pos='C5';E.apply(s,'rest');assert.equal(h.hp,12);assert.equal(h.energy,4);});
test('Co-located party is involved and enemy HP scales only once',()=>{const s=E.create([0,1,2]);s.heroes[0].pos=s.heroes[1].pos='A2';E.apply(s,'engage');assert.deepEqual(s.battle.participants,[0,1]);assert.equal(s.enemies[0].max,13);E.apply(s,'retreat');assert.equal(s.actions,0);E.apply(s,'end');s.heroes[1].pos='A2';E.apply(s,'engage');assert.equal(s.enemies[0].max,13);});
test('Stances change dice and focus spends energy once',()=>{const s=E.create([1]);E.hero(s).pos='A2';E.apply(s,'engage');E.apply(s,'stance',{hero:0,stance:'focus'});assert.deepEqual(E.pool(s,0,'focus'),[0,5,0]);E.apply(s,'roll',{},high);assert.equal(E.hero(s).energy,3);assert.equal(s.battle.dice.length,5);assert.throws(()=>E.apply(s,'roll'));});
test('Reroll is per-owner, limited and consumes energy',()=>{const s=E.create([0]);E.hero(s).pos='A2';E.apply(s,'engage');E.apply(s,'roll',{},low);E.apply(s,'reroll',{index:0},high);assert.equal(s.battle.dice[0].value,6);assert.equal(E.hero(s).energy,3);assert.throws(()=>E.apply(s,'reroll',{index:0}));assert.throws(()=>E.apply(s,'reroll',{index:1}));});
test('Gear improves reroll limits and success thresholds are color-specific',()=>{const s=E.create([0]),h=E.hero(s);h.bag=[4];E.apply(s,'equip',{id:4});h.pos='A2';E.apply(s,'engage');E.apply(s,'roll',{},low);E.apply(s,'reroll',{index:0},high);E.apply(s,'reroll',{index:1},high);assert.equal(h.energy,2);s.battle.dice=[{hero:0,color:0,value:3},{hero:0,color:1,value:3},{hero:0,color:2,value:4}];assert.deepEqual(E.preview(s),{physical:0,magic:1,damage:1,blocks:{0:2}});});
test('Enemy armor blocks physical but not magic; ward does reverse',()=>{const s=E.create([1]);E.hero(s).pos='E3';E.apply(s,'engage');s.battle.dice=[{hero:0,color:0,value:4},{hero:0,color:1,value:6}];assert.equal(E.preview(s).damage,2);s.battle.enemy='knight';assert.equal(E.preview(s).damage,2);});
test('Wolf has piercing bleed; troll regenerates; knight drains energy',()=>{for(const [id,round] of [['wolf',2],['troll',2],['knight',1]]){const s=E.create([0]);E.hero(s).pos=E.enemyDefs.find(e=>e.id===id).pos;E.apply(s,'engage');s.battle.round=round;const before=E.hero(s).hp;E.apply(s,'roll',{},low);s.battle.dice=[{hero:0,color:2,value:6}];E.apply(s,'resolve');if(id==='wolf')assert.equal(E.hero(s).hp,before-3);if(id==='knight')assert.equal(E.hero(s).energy,3);if(id==='troll')assert.equal(E.hero(s).hp,before-2);}});
test('Recover heals every living participant before enemy retaliation',()=>{const s=E.create([3,0]);s.heroes.forEach(h=>{h.pos='A2';h.hp=5;});E.apply(s,'engage');E.apply(s,'stance',{hero:0,stance:'recover'});E.apply(s,'roll',{},low);E.apply(s,'resolve');assert.equal(s.heroes[0].hp,6);assert.equal(s.heroes[1].hp,9);assert.equal(s.heroes[0].energy,3);});
test('Tank selection chooses most defense; boss breath hits everyone',()=>{const s=E.create([1,0]);s.heroes.forEach(h=>h.pos='D1');s.seals=2;s.heroes[0].xp=6;E.apply(s,'engage');s.battle.round=3;E.apply(s,'roll',{},low);s.battle.dice=[{hero:1,color:2,value:6}];E.apply(s,'resolve');assert.equal(s.heroes[0].hp,4);assert.equal(s.heroes[1].hp,9);});
test('Boss gates level+seals; third seal weakens it; enraged intent rises',()=>{const s=E.create([0]);E.hero(s).pos='D1';assert.throws(()=>E.apply(s,'engage'));s.seals=2;assert.throws(()=>E.apply(s,'engage'));s.seals=3;E.hero(s).xp=6;E.apply(s,'engage');assert.equal(s.enemies[3].max,24);assert.equal(E.intent(s).damage,6);s.enemies[3].hp=12;assert.equal(E.intent(s).damage,8);});
test('Victory awards personal XP and hunt progress only to participants',()=>{const s=E.create([0,1]);E.apply(s,'accept',{id:'wolves'});fight(s,'wolf');assert.equal(s.seals,1);assert.equal(s.heroes[0].xp,1);assert.equal(s.heroes[1].xp,0);assert.equal(s.heroes[0].quests.find(q=>q.id==='wolves').ready,true);assert.equal(s.battle,null);});
test('Retreat preserves enemy damage and cannot escape after rolling',()=>{const s=E.create([0]);E.hero(s).pos='A2';E.apply(s,'engage');E.apply(s,'roll',{},low);assert.throws(()=>E.apply(s,'retreat'));s.battle.dice=[{hero:0,color:0,value:4}];E.apply(s,'resolve');const hp=s.enemies[0].hp;E.apply(s,'retreat');assert.equal(s.enemies[0].hp,hp);assert.equal(E.hero(s).pos,'C5');assert.equal(s.actions,0);});
test('Fallen active hero can finish world turn; revival uses full turn',()=>{const s=E.create([0,1]);s.heroes[0].hp=0;E.apply(s,'end');assert.equal(s.active,1);E.apply(s,'end');E.apply(s,'end');assert.equal(s.active,0);assert.equal(s.heroes[0].hp,4);assert.equal(s.actions,0);});
test('Party wipe and world time are actual losses',()=>{const s=E.create([1]);E.hero(s).pos='A2';E.hero(s).hp=1;E.apply(s,'engage');E.apply(s,'roll',{},low);E.apply(s,'resolve');assert.equal(s.outcome,'lose');const t=E.create([0]);for(let i=0;i<20;i++)E.apply(t,'end');assert.equal(t.outcome,'lose');assert.equal(t.round,20);assert.ok(E.validate(t));});
test('World events apply every third round and saves resume rolled battles',()=>{const s=E.create([0],high);E.apply(s,'end');assert.equal(s.event,null);E.apply(s,'end');assert.equal(s.event,0);assert.equal(E.hero(s).gold,5);E.hero(s).pos='A2';E.apply(s,'engage');E.apply(s,'roll',{},high);const restored=JSON.parse(JSON.stringify(s));assert.ok(E.validate(restored));E.apply(restored,'resolve');assert.ok(restored.log.length);assert.equal(E.validate({...restored,version:1}),false);});
test('Complete real solo campaign: quests, build, seals, boss, win',()=>{const s=E.create([0],high),h=E.hero(s);walk(s,'C4');action(s,'explore');walk(s,'C5');action(s,'claim',{id:'herbs',gear:0});E.apply(s,'equip',{id:0});E.apply(s,'talent',{index:0});E.apply(s,'accept',{id:'caravan'});E.apply(s,'accept',{id:'wolves'});walk(s,'A4');action(s,'claim',{id:'caravan',gear:4});E.apply(s,'equip',{id:4});walk(s,'A2');if(!s.actions)E.apply(s,'end');E.apply(s,'engage');while(s.battle){E.apply(s,'roll',{},high);E.apply(s,'resolve');}walk(s,'A4');action(s,'claim',{id:'wolves',gear:2});E.apply(s,'equip',{id:2});E.apply(s,'talent',{index:2});E.apply(s,'accept',{id:'mine'});walk(s,'E5');action(s,'rest');walk(s,'E3');if(!s.actions)E.apply(s,'end');E.apply(s,'engage');while(s.battle){E.apply(s,'roll',{},high);E.apply(s,'resolve');}walk(s,'E5');action(s,'claim',{id:'mine',gear:6});E.apply(s,'equip',{id:6});E.apply(s,'talent',{index:4});action(s,'rest');walk(s,'D1');if(!s.actions)E.apply(s,'end');E.apply(s,'engage');while(s.battle){E.apply(s,'roll',{},high);E.apply(s,'resolve');}assert.equal(s.outcome,'win');assert.equal(h.completed.length,4);assert.ok(s.round<=20);assert.ok(h.talents.length===3);});
test('Equipment trade consumes action and clears transferred equipped slot',()=>{const s=E.create([0,1]);E.hero(s).bag=[0];E.apply(s,'equip',{id:0});E.apply(s,'trade',{id:0,hero:1});assert.deepEqual(s.heroes[1].bag,[0]);assert.equal(s.heroes[0].equipment.weapon,null);assert.equal(s.actions,2);assert.throws(()=>E.apply(s,'trade',{id:0,hero:1}));});
test('Saved-state validation rejects malformed quest, equipment and battle records',()=>{for(const mutate of [s=>s.heroes[0].quests=[{id:'unknown',ready:false}],s=>s.heroes[0].equipment.weapon=99,s=>s.heroes[0].energy=99,s=>s.heroes[0].talents=[99],s=>s.enemies[0].hp=-1,s=>s.eventDeck=[0]]){const s=E.create([0]);mutate(s);assert.equal(E.validate(s),false);}});
console.log(`PASS: ${count} campaign engine scenarios`);
