"""Start the HTTP server, then run this script; requires Playwright and Chromium."""
import os,shutil
from playwright.sync_api import sync_playwright

checks=[]
def check(name,condition):
    if not condition:raise AssertionError(name)
    checks.append(name)

with sync_playwright() as p:
    chromium=shutil.which('chromium')
    browser=p.chromium.launch(headless=True,**({'executable_path':chromium} if chromium else {}))
    context=browser.new_context(viewport={'width':1024,'height':1366},has_touch=True,is_mobile=True)
    page=context.new_page();errors=[]
    page.on('pageerror',lambda e:errors.append(str(e)))
    page.add_init_script('Math.random = () => 0.999999;')
    page.goto(os.environ.get('ELDERFALL_TEST_URL','http://127.0.0.1:8000/'))
    check('Initial party selection',page.locator('#setup').is_visible())
    check('Explains game and victory condition','협동 RPG 보드게임' in page.locator('.intro').inner_text() and '드래곤 처치' in page.locator('.game-explainer').inner_text())
    check('World-map illustration available',page.evaluate("fetch('assets/world-map.png').then(r=>r.ok)"))
    check('Hero artwork available',page.evaluate("fetch('assets/heroes.png').then(r=>r.ok)"))
    check('Enemy artwork available',page.evaluate("fetch('assets/enemies.png').then(r=>r.ok)"))
    page.screenshot(path='/tmp/elderfall-new-home.png',full_page=True,animations='disabled')
    page.locator('#class-picker input[value="0"]').uncheck()
    page.locator('#start').tap()
    check('Empty party rejected',bool(page.locator('#setup-error').inner_text()))
    page.locator('#class-picker input[value="0"]').check();page.locator('#start').tap()
    check('Solo campaign starts',page.locator('#game').is_visible() and '남은 행동 4' in page.locator('#game-status').inner_text())
    check('25 touch tiles',page.locator('#board .tile').count()==25)
    check('Three quest objectives and visible rewards',page.locator('#quests .quest-card').count()==3 and '전리품 2장' in page.locator('#quests').inner_text())
    page.locator('[data-open="quest-modal"]').tap()
    page.locator('#quests .quest-card').nth(1).tap()
    check('Pinning quest updates destination without spending actions','E3' in page.locator('#next-goal').inner_text() and '남은 행동 4' in page.locator('#game-status').inner_text() and 'E3' in page.locator('.quest-destination .coord').inner_text())
    page.locator('[data-open="quest-modal"]').tap()
    page.locator('#quests .quest-card').nth(0).tap()
    check('First move guidance highlights B5','B5' in page.locator('#next-goal').inner_text() and 'B5' in page.locator('.suggested .coord').inner_text())
    page.screenshot(path='/tmp/elderfall-first-play.png',full_page=True,animations='disabled')
    check('Nonadjacent tile disabled',page.get_by_role('button',name='A1 황야',exact=True).is_disabled())
    check('Smart UI disables out-of-range attack',page.locator('#attack').is_disabled() and '남은 행동 4' in page.locator('#game-status').inner_text())
    check('Smart UI suggests next objective','남은 지역 3곳' in page.locator('#next-goal').inner_text())
    def next_turn():
        if '남은 행동 0' in page.locator('#game-status').inner_text():page.locator('#end-turn').tap()
    def move(pos):
        next_turn()
        page.locator('#board button').filter(has=page.locator('.coord',has_text=pos)).tap()
        check('Move '+pos,pos in page.locator('#active-info').inner_text())
    def fight(pos):
        while page.locator('#enemy-target option[value="'+pos+'"]').count():
            next_turn();page.select_option('#enemy-target',pos);page.locator('#attack').tap()
            while page.locator('#reward').is_visible():page.locator('#reward').get_by_role('button',name='기사에게').tap()
    for pos in ['B5','A5','A4','A3','A2']:move(pos)
    check('Entering enemy tile opens battle scene',page.locator('#combat-scene').is_visible() and '가시늑대' in page.locator('#combat-title').inner_text())
    for width,height in [(320,800),(390,844),(768,1024),(1024,768),(1024,1366),(1366,1024)]:
        page.set_viewport_size({'width':width,'height':height})
        check(f'Battle fits without page scroll {width}x{height}',page.evaluate("document.documentElement.scrollHeight<=innerHeight&&['#combat-scene','#attack','#end-turn','#back-board','#enemy-target'].every(s=>{const r=document.querySelector(s).getBoundingClientRect();return r.width>0&&r.height>0&&r.top>=0&&r.bottom<=innerHeight&&r.right<=innerWidth})"))
    page.set_viewport_size({'width':1024,'height':768})
    page.screenshot(path='/tmp/elderfall-battle.png',full_page=True,animations='disabled')
    page.locator('#back-board').tap()
    check('Battle can return to map for retreat',page.locator('#board').is_visible() and page.locator('#enter-battle').is_visible())
    page.locator('#enter-battle').tap()
    check('Battle can reopen without spending an action',page.locator('#combat-scene').is_visible())
    page.locator('#back-board').tap()
    move('A3')
    check('Actual retreat spends action and leaves combat',not page.locator('#combat-scene').is_visible() and 'A3' in page.locator('#active-info').inner_text())
    move('A2')
    check('Returning to enemy tile reopens battle',page.locator('#combat-scene').is_visible())
    page.locator('#attack').tap()
    check('Battle shows rolled die and damage',page.locator('#die-face i').count()==6 and '체력 1/4' in page.locator('#enemy-detail').inner_text() and '−3 HP' in page.locator('#battle-result').inner_text())
    page.screenshot(path='/tmp/elderfall-battle-hit.png',animations='disabled')
    page.locator('#end-turn').tap()
    check('Enemy retaliation shows damage and updated hero HP','적의 반격' in page.locator('#battle-result').inner_text() and '체력 8/10' in page.locator('#active-info').inner_text())
    fight('A2')
    check('Defeating enemy returns to the board',page.locator('#board').is_visible() and not page.locator('#combat-scene').is_visible())
    check('First seal, XP and loot', '봉인 1/3' in page.locator('#game-status').inner_text() and '레벨 2' in page.locator('#party').inner_text() and page.locator('#inventory .item-row').count()==2)
    page.locator('[data-open="bag-modal"]').tap()
    check('Bag opens over table with loot cards',page.locator('#bag-modal').is_visible() and page.locator('#inventory .loot-medallion').count()==2)
    page.keyboard.press('Escape')
    check('Closing bag restores table and focus',not page.locator('#bag-modal').is_visible() and page.locator('[data-open="bag-modal"]').evaluate('(b)=>b===document.activeElement'))
    page.locator('[data-open="rules-modal"]').tap()
    check('Rules open in overlay',page.locator('#rules-modal').is_visible())
    page.locator('[data-close="rules-modal"]').tap()
    check('Rules close without losing progress',not page.locator('#rules-modal').is_visible() and '봉인 1/3' in page.locator('#game-status').inner_text())
    check('Completed quest visibly marked',page.locator('#quests .quest-card.completed').count()==1)
    page.reload()
    check('Automatic save resumes',page.locator('#game').is_visible() and '봉인 1/3' in page.locator('#game-status').inner_text() and 'A2' in page.locator('#active-info').inner_text())
    for pos in ['B2','B1']:move(pos)
    fight('B1')
    for pos in ['C1','D1','E1','E2','E3']:move(pos)
    fight('E3')
    check('Three seals and level 3', '봉인 3/3' in page.locator('#game-status').inner_text() and '레벨 3' in page.locator('#party').inner_text())
    for pos in ['D3','D2','D1']:move(pos)
    next_turn();check('Dragon summon enabled',page.locator('#summon').is_enabled());page.locator('#summon').tap()
    fight('D1')
    check('Whole campaign wins through touch UI','승리!' in page.locator('#outcome').inner_text())
    check('Finished game disables actions',page.locator('#attack').is_disabled() and page.locator('#end-turn').is_disabled())
    page.reload();check('Victory persists after reload','승리!' in page.locator('#outcome').inner_text())
    page.locator('[data-close="result-modal"]').tap()
    page.once('dialog',lambda d:d.dismiss());page.locator('#new-game').tap();check('Cancelled restart preserves game',page.locator('#game').is_visible())
    page.once('dialog',lambda d:d.accept());page.locator('#new-game').tap();check('Confirmed restart returns to selection',page.locator('#setup').is_visible())
    for i in range(4):page.locator(f'#class-picker input[value="{i}"]').check()
    page.locator('#start').tap()
    page.locator('#party .hero-panel').nth(2).tap()
    check('Hero card can be inspected','궁수' in page.locator('#detail-hero-name').inner_text() and '조준 사격' in page.locator('#hero-detail').inner_text())
    page.keyboard.press('Escape')
    check('Hero inspection closes without spending actions',not page.locator('#hero-modal').is_visible() and '남은 행동 3' in page.locator('#game-status').inner_text())
    check('Four-player party starts',page.locator('#party .hero-panel').count()==4 and '남은 행동 3' in page.locator('#game-status').inner_text())
    page.locator('#end-turn').tap();check('Turn passes to mage','마법사' in page.locator('#turn-title').inner_text())
    page.locator('#end-turn').tap();page.locator('#end-turn').tap();page.locator('#end-turn').tap()
    check('Enemy phase and rotating leader','라운드 2/10' in page.locator('#game-status').inner_text() and '마법사' in page.locator('#turn-title').inner_text())
    for width,height in [(320,800),(390,844),(768,1024),(1024,768),(1024,1366),(1366,1024)]:
        page.set_viewport_size({'width':width,'height':height})
        check(f'No horizontal overflow {width}x{height}',page.evaluate('document.documentElement.scrollWidth <= window.innerWidth'))
        check(f'No page vertical scroll {width}x{height}',page.evaluate('document.documentElement.scrollHeight <= window.innerHeight'))
        check(f'Board and action dock fit {width}x{height}',page.evaluate("['#board','#attack','#end-turn','#party'].every(s=>{const r=document.querySelector(s).getBoundingClientRect();return r.width>0&&r.height>0&&r.top>=0&&r.bottom<=innerHeight&&r.right<=innerWidth})"))
    page.set_viewport_size({'width':1024,'height':768});page.screenshot(path='/tmp/elderfall-ipad.png',full_page=True,animations='disabled')
    # Isolated UI fixtures exercise miss, healing and item feedback.
    page.evaluate("state=E.create([3]);state.heroes[0].pos='A2';state.heroes[0].hp=5;scenePreference='auto';resultDismissed=false;Math.random=()=>0;render();")
    page.locator('#attack').tap()
    check('Miss displays die and leaves enemy HP unchanged','빗나갔습니다' in page.locator('#battle-result').inner_text() and '체력 4/4' in page.locator('#enemy-detail').inner_text() and page.locator('#die-face i').count()==1)
    page.select_option('#hero-target','0');page.locator('#skill').tap()
    check('Priest can heal within battle','체력 8/9' in page.locator('#active-info').inner_text() and page.locator('#skill').is_disabled())
    page.evaluate("state.heroes[0].items=[0];render();")
    page.locator('[data-open="bag-modal"]').tap();page.locator('#inventory').get_by_role('button',name='사용',exact=True).tap()
    check('Potion closes bag, heals and does not show attack feedback',not page.locator('#bag-modal').is_visible() and '체력 9/9' in page.locator('#active-info').inner_text() and not page.locator('#battle-result').inner_text())
    for width,height in [(768,1024),(1024,768)]:
        page.set_viewport_size({'width':width,'height':height})
        check(f'Healing target fits battle {width}x{height}',page.evaluate("['#hero-target','#attack','#end-turn'].every(s=>{const r=document.querySelector(s).getBoundingClientRect();return r.width>0&&r.height>0&&r.top>=0&&r.bottom<=innerHeight&&r.right<=innerWidth})"))
    check('No JavaScript runtime errors',not errors)
    browser.close()
print(f'PASS: {len(checks)} browser checks')
for name in checks:print(' PASS:',name)
