'use strict';
const assert=require('node:assert/strict'),E=require('../game-engine.js');let count=0;
const high=()=>.999999,low=()=>0;
function test(name,fn){fn();count++;console.log('PASS',name);}
function encounter(ids=[0],enemy='troll'){const s=E.create(ids);s.heroes.forEach(h=>h.pos=E.enemyDefs.find(e=>e.id===enemy).pos);E.apply(s,'engage');E.apply(s,'roll',{},high);return s;}
function die(s,index,color,value,owner=0){s.battle.dice[index]={hero:owner,color,value,rerolled:false};}
function assign(s,id,index,target=0,owner=0){E.apply(s,'assign',{owner,id,index,target});}
function rejectsAtomically(s,type,arg){const before=JSON.stringify(s);assert.throws(()=>E.apply(s,type,arg));assert.equal(JSON.stringify(s),before);}
test('Assigned attack consumes base contribution and armor penetration is previewed',()=>{const s=encounter();s.battle.dice=[];die(s,0,0,4);assert.equal(E.preview(s).physical,2);assign(s,'strike',0);assert.equal(E.preview(s).physical,0);assert.equal(E.tacticalPreview(s).damage,3);assert.equal(s.heroes[0].energy,4);const hp=s.enemies[1].hp;E.apply(s,'resolve');assert.equal(s.enemies[1].hp,hp-3);assert.equal(s.heroes[0].energy,3);});
test('Failed eyes become protection; targeted defense selects the front hero',()=>{const s=encounter([0,1]);s.battle.dice=[];die(s,0,0,2);assign(s,'protect',0,1);const p=E.tacticalPreview(s);assert.equal(p.blocks[1],3);assert.equal(p.front,1);assert.equal(p.after[0],12);assert.equal(p.after[1],7);E.apply(s,'resolve');assert.equal(s.heroes[0].hp,12);assert.equal(s.heroes[1].hp,7);});
test('All illegal color, eye, ownership, target, index and locked-level choices leave state intact',()=>{const s=encounter([0,1]);die(s,0,1,6);die(s,1,0,1);die(s,2,0,6);for(const a of [{owner:0,id:'strike',index:0,target:0},{owner:0,id:'strike',index:1,target:0},{owner:1,id:'fire',index:0,target:1},{owner:0,id:'strike',index:2,target:1},{owner:0,id:'strike',index:2.2,target:0},{owner:0,id:'whirlwind',index:2,target:0},{owner:0,id:'unknown',index:2,target:0}])rejectsAtomically(s,'assign',a);});
test('A die cannot feed two techniques; unassignment restores normal contribution',()=>{const s=encounter();s.battle.dice=[];die(s,0,2,4);assign(s,'counter',0);assert.equal(E.preview(s).blocks[0],undefined);assert.equal(E.tacticalPreview(s).blocks[0],3);rejectsAtomically(s,'assign',{owner:0,id:'protect',index:0,target:0});E.apply(s,'unassign',{owner:0,id:'counter'});assert.equal(E.preview(s).blocks[0],2);assert.equal(s.heroes[0].energy,4);});
test('Reassigning one technique replaces its die without duplicate costs',()=>{const s=encounter();die(s,0,0,4);die(s,1,0,5);assign(s,'strike',0);assign(s,'strike',1);assert.equal(s.battle.assignments.length,1);assert.equal(s.battle.assignments[0].index,1);assert.equal(E.tacticalPreview(s).costs[0],1);});
test('Committed energy prevents rerolls that would invalidate planned skills',()=>{const s=encounter();die(s,0,0,4);s.heroes[0].energy=1;assign(s,'strike',0);rejectsAtomically(s,'reroll',{index:1});rejectsAtomically(s,'reroll',{index:0});E.apply(s,'unassign',{owner:0,id:'strike'});E.apply(s,'reroll',{index:0},low);assert.equal(s.heroes[0].energy,0);});
test('Cooldown skips the next round, survives save, and returns on round three',()=>{const s=encounter();s.battle.dice=[];die(s,0,0,1);assign(s,'protect',0);E.apply(s,'resolve');assert.equal(s.battle.round,2);assert.equal(s.battle.cooldowns['0:protect'],3);const saved=JSON.parse(JSON.stringify(s));assert.ok(E.validate(saved));E.apply(s,'roll',{},low);rejectsAtomically(s,'assign',{owner:0,id:'protect',index:0,target:0});E.apply(s,'resolve');E.apply(s,'roll',{},low);assign(s,'protect',0);});
test('Level three unlocks burst with combined energy commitments',()=>{const s=encounter();s.heroes[0].xp=6;die(s,0,0,6);die(s,1,0,5);s.heroes[0].energy=2;assign(s,'whirlwind',0);rejectsAtomically(s,'assign',{owner:0,id:'strike',index:1,target:0});E.apply(s,'unassign',{owner:0,id:'whirlwind'});assign(s,'strike',1);s.heroes[0].energy=3;assign(s,'whirlwind',0);assert.equal(E.tacticalPreview(s).costs[0],3);});
test('Priest target heals before retaliation and preview exactly matches actual HP',()=>{const s=encounter([3,0]);s.heroes[0].hp=4;s.heroes[1].hp=3;s.battle.dice=[];die(s,0,1,1);die(s,1,2,1);assign(s,'heal',0,1);assign(s,'ward',1,1);const p=E.tacticalPreview(s);assert.equal(p.after[1],7);E.apply(s,'resolve');assert.equal(s.heroes[1].hp,p.after[1]);assert.equal(s.heroes[0].hp,p.after[0]);assert.equal(s.heroes[0].energy,3);});
test('Mage debuff reduces piercing damage and conversion cannot fund costs retroactively',()=>{const s=encounter([1],'wolf');s.battle.round=2;s.battle.dice=[];die(s,0,1,1);assign(s,'frost',0);assert.equal(E.tacticalPreview(s).incoming[0],1);E.apply(s,'resolve');assert.equal(s.heroes[0].hp,8);const t=encounter([1]);t.heroes[0].energy=0;die(t,0,1,1);die(t,1,1,4);assign(t,'channel',0);rejectsAtomically(t,'assign',{owner:0,id:'fire',index:1,target:0});E.apply(t,'resolve');assert.equal(t.heroes[0].energy,1);});
test('Victory cancels retaliation and cannot be resolved twice',()=>{const s=encounter();s.enemies[1].hp=1;s.battle.dice=[];die(s,0,0,6);assign(s,'strike',0);const hp=s.heroes[0].hp;assert.equal(E.tacticalPreview(s).incoming[0],0);E.apply(s,'resolve');assert.equal(s.heroes[0].hp,hp+2);assert.equal(s.battle,null);rejectsAtomically(s,'resolve',{});});
test('Malformed commitments, duplicate dice, bad cooldowns and overspend fail save validation',()=>{const s=encounter();die(s,0,0,5);assign(s,'strike',0);assert.ok(E.validate(s));for(const mutate of [t=>t.battle.assignments[0].index=99,t=>t.battle.assignments.push({...t.battle.assignments[0]}),t=>t.heroes[0].energy=0,t=>t.battle.cooldowns['0:strike']=99,t=>t.battle.assignments[0].target=9]){const t=JSON.parse(JSON.stringify(s));mutate(t);assert.equal(E.validate(t),false);}});
test('Old rolled records resume without new fields or changing saved dice',()=>{const s=encounter();delete s.battle.assignments;delete s.battle.cooldowns;assert.ok(E.validate(s));assert.equal(E.tacticalPreview(s).damage,E.preview(s).damage);E.apply(s,'resolve');assert.ok(E.validate(s));});
test('Every class has a valid starter attack and utility using its own pool',()=>{for(let ci=0;ci<4;ci++){const s=encounter([ci]);const available=E.techniques[ci].filter(t=>!t.level);assert.equal(available.length,3);assert.ok(available.some(t=>s.battle.dice.some((d,i)=>!E.skillReason(s,0,t.id,i,0))));for(const t of available){s.battle.assignments=[];const color=t.color??0;die(s,0,color,t.max||t.min||1);assign(s,t.id,0);assert.ok(E.validate(s));assert.ok(E.tacticalPreview(s).damage>=0);}}});
console.log(`PASS: ${count} technique scenarios`);
